<?php

 
$hotels = [

    ["name"=>"AC Hotel",
    "dailyRate"=>1220,
    "pool"=>"available",
    "bar"=>"available",
    "kidFriendly"=>"false",
    "breakfast"=>"available"],
    ["name"=>"Lagoon Beach Hotel",
    "dailyRate"=>814,
    "pool"=>"available",
    "bar"=>"available",
    "kidFriendly"=>"true",
    "breakfast"=>"available"],
    ["name"=>"HOTEL SKY",
    "dailyRate"=>734,
    "pool"=>"available",
    "bar"=>"available",
    "kidFriendly"=>"false",
    "breakfast"=>"available"],
    ["name"=>"Vineyard Hotel"
    ,"dailyRate"=>2075,
    "pool"=>"available",
    "bar"=>"available",
    "kidFriendly"=>"false",
    "breakfast"=>"available"],
    ["name"=>"City Lodge Hotel V&A Waterfront",
    "dailyRate"=>575,
    "pool"=>"unavailable",
    "bar"=>"available",
    "kidFriendly"=>"true",
    "breakfast"=>"unavailable"],
    ["name"=>"The Westin",
    "dailyRate"=>1935,
    "pool"=>"available",
    "bar"=>"available",
    "kidFriendly"=>"false",
    "breakfast"=>"available"],
    ["name"=>"Waterfront Village",
    "dailyRate"=>1268,
    "pool"=>"available",
    "bar"=>"available",
    "kidFriendly"=>"true",
    "breakfast"=>"unavailable"],
    ["name"=>"Cresta Grande",
    "dailyRate"=>700,
    "pool"=>"available",
    "bar"=>"available",
    "kidFriendly"=>"false",
    "breakfast"=>"available"]
];
?>